### ISSUE TITLE
"bed_file" and "region" parameters

### ISSUE THREAD

**Issue by hj6-sanger** [AlexandrovLab/SigProfilerSimulator#2]
Dear author. 

Thanks for making this wonderful tool. 
I have questions regarding this tool.

I would like to simulate mutations within genes. 
In order to do this, I inputted gene regions in "bed_file".
(sigSim.SigProfilerSimulator("SIMUL", "./up_gene", "GRCh38", contexts=["96"],simulations=120,bed_file="./updown_bed_canonincal_hg38")
However, this tool seemed to simulate a subset of mutations with this parameter. 
(e.g., the number of total mutations within genes is around 10,000, but, each maf file contains about 700 mutations.)

Next, I inputted "BED_GRCh38_proportions", which seemed to be generated when using "bed_file" parameter, in the region parameter. (sigSim.SigProfilerSimulator("SIMUL", "./up_gene", "GRCh38", contexts=["96"],simulations=120,region="BED_GRCh38_proportions")

However, this approach caused the following error. 
Could you tell me the best way to simulate mutations within genes?

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/lustre/scratch117/casm/team78/hj6/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/lustre/scratch117/casm/team78/hj6/anaconda3/lib/python3.7/site-packages/SigProfilerSimulator/mutational_simulator.py", line 2349, in simulator
    mutNuc = ''.join([tsb_ref[base][1] for base in sequence[random_number - mut_start:random_number + mut_start+1]])
  File "/lustre/scratch117/casm/team78/hj6/anaconda3/lib/python3.7/site-packages/SigProfilerSimulator/mutational_simulator.py", line 2349, in <listcomp>
    mutNuc = ''.join([tsb_ref[base][1] for base in sequence[random_number - mut_start:random_number + mut_start+1]])
KeyError: 51
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lustre/scratch117/casm/team78/hj6/anaconda3/lib/python3.7/site-packages/SigProfilerSimulator/SigProfilerSimulator.py", line 479, in SigProfilerSimulator
    r.get()
  File "/lustre/scratch117/casm/team78/hj6/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
KeyError: 51

**Comment by cutleraging** [comment]
Sorry to re-open this question, but I am still a bit confused about the difference between the `bed_file` and `region` parameters. Could this please be explained? I wish to randomly shuffle mutations from a given sample but only within regions which were sufficiently covered.
